### ISSUE TITLE
Not an issue, just a question.

### ISSUE THREAD

**Issue by Jbizl** [i1ya/freqtrade-strategies#2]
Hi, I've downloaded one of your freqtrade strategies, CombinedBinHClucAndMADV9, I've had it on dry run for some time now but it doesn't seem to be doing anything, I've also configured my config.json file to your recommendations. Can you offer any advice on this?

**Comment by i1ya** [comment]
Hi!
Thanks for using my strategies.
For now, I don't have enough resources to run CombinedBinHClucAndMADV9.
But, according to backtests CombinedBinHClucAndMADV9 made the last trade 2021-06-25 at 13:10:00+00:00.

{
   "pair":"SHIB/USDT",
   "open_date":"2021-06-25 13:10:00+00:00",
   "close_date":"2021-06-25 13:50:00+00:00",
   "open_rate":7.25e-06,
   "close_rate":7.37e-06,
   "fee_open":0.001,
   "fee_close":0.001,
   "trade_duration":40,
   "profit_ratio":0.01452065,
   "profit_abs":3.60226297,
   "sell_reason":"roi",
}

It's ok to get 0 trades if you run your bot after that date.

**Comment by Jbizl** [comment]
Hi, thanks for the response. I've backtested this strategy over the past 60 days and the results are quite impressive! I've came to the conclusion that current market conditions are stopping the bot from doing anything, which is excellent. One thing I'd like to ask is that you can put some instructions in the strategy to change the config settings:

bid_strategy.price_side = "ask" ask_strategy.price_side ="bid"

need to be set respectively for the bot to run otherwise it will throw up errors, unless these settings were not meant to be changed and something else needs looking at?

Other than that it's great, once the markets pick up I will certainly be crediting your wallets with some contributions for your efforts.

**Comment by i1ya** [comment]
Well, good point. I'll add this info to FAQ.

**Comment by i1ya** [comment]
Add info to the ReadMe.
