### ISSUE TITLE
custom_trade_exit function is disabled?

### ISSUE THREAD

**Issue by Heistergand** [i1ya/freqtrade-strategies#7]
In BigZ07.py, the custom_trade_exit function is always returning `True `(line 165) but after that there is more code which will never be executed. Is this intentionally?

**Comment by i1ya** [comment]
Yes.
I test some ideas from time to time. Some things work and some don't. I leave in the code those ideas that seemed interesting to me, but still don't work well.

**Comment by Heistergand** [comment]
closed: not an issue
